[analysis]
ifos=['H1','L1','V1']
singularity=False
osg=False

[condor]
accounting_group=ligo.sim.o4.cbc.pe.rift
accounting_group_user=aasim.jan

[datafind]
url-type = file
types = {'H1': 'O4MDC', 'L1': 'O4MDC', 'V1': 'O4MDC'}

[data]
channels = {'H1': 'H1:FAKE-STRAIN', 'L1': 'L1:FAKE-STRAIN', 'V1': 'V1:FAKE-STRAIN'}

[lalinference]
flow = {'H1': 20.0, 'L1': 20.0, 'V1': 20.0}
fhigh = {'H1': 1024.0, 'L1': 1024.0, 'V1': 1024.0}

[engine]
# Approximant
fref=10

# Distance 
distance-max = 5000

# Data 
seglen = 8
srate = 2048.0

[rift-pseudo-pipe]
# ILE
internal-ile-use-lnL=True
internal-ile-request-disk="8M"
internal-ile-request-memory="8192"
ile-runtime-max-minutes=700
ile-jobs-per-worker=18
ile-n-eff=20
ile-sampler-method="AV"
ile-copies=1
ile-no-gpu=True
ile-retires=3
ile-distance-prior="pseudo_cosmo"
#internal-sky-network-coordinates=True
#internal-ile-rotate-phase=True

# Extrinsic ILE
internal-last-iteration-extrinsic-samples-per-ile=20
add-extrinsic=True
batch-extrinsic=True
add-extrinsic-time-resampling=True

# CIP
internal-cip-use-lnL=True
cip-fit-method="rf"
cip-sampler-method="AV"
cip-explode-jobs=300
cip-explode-jobs-last=300
n-output-samples=10000
n-output-samples-last=10000
cip-sigma-cut=0.4
#force-ecc-min=0.0
#force-ecc-max=0.28
spin-magnitude-prior='zprior_aligned'
force_chi_max=0.99
force_chi_small_max=0.99
force-mc-range=[30,55]
force-eta-range=[0.15,0.25]
#internal-puff-transverse=True

# Approximant
approx="NRHybSur3dq8"
l-max=5
fmin-template=10
#use-gwsignal=True
#use-gwsurrogate=True

# Algorithm
internal-test-convergence-threshold=0.001
internal-flat-stratergy=True
#assume-eccentric=True
#use-meanPerAno=True
internal-force-iterations=7
internal-loud-signal-mitigation-suite=True
internal-n-evaluations-per-iteration=5000
internal-use-aligned-phase-coordinates=True
#assume-precessing=True
#internal-propose-converge-last-stage=True
#calibration="C01-deglitched"
#internal-correlate-default=True
#internal-use-rescaled-transverse-spin-coordinates=True

# OSG
use_osg=False
use_osg_file_transfer=False
use_osg_cip=False

